// <auto-generated />
using System;
using Inventory.PersistenceService.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.PersistenceService.Migrations
{
    [DbContext(typeof(InventoryDBContext))]
    [Migration("20260104082027_04012025")]
    partial class _04012025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.DomainObjects.AisleDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.Property<int>("InventoryTypeId")
                        .HasColumnType("INT")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<int>("StorageSectionId")
                        .HasColumnType("INT")
                        .HasColumnOrder(4);

                    b.Property<int>("StorageTypeId")
                        .HasColumnType("INT")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(10);

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_aisle_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_aisle_name");

                    b.HasIndex("StorageSectionId");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_aisle_warehouse_id");

                    b.ToTable("Aisle", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.AllocationDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CreatedBy")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("CreatedOn")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MaterialBatchId")
                        .HasColumnType("INT")
                        .HasColumnName("MaterialBatchId")
                        .HasColumnOrder(4);

                    b.Property<int>("OrderId")
                        .HasColumnType("INT")
                        .HasColumnName("OrderId")
                        .HasColumnOrder(2);

                    b.Property<int>("ProductId")
                        .HasColumnType("INT")
                        .HasColumnName("ProductId")
                        .HasColumnOrder(3);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("Decimal(10,2)")
                        .HasColumnName("Quantity")
                        .HasColumnOrder(5);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)")
                        .HasDefaultValue("Allocated")
                        .HasColumnName("Status")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UpdatedBy")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UpdatedOn")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_allocation_id");

                    b.HasIndex("MaterialBatchId")
                        .HasDatabaseName("IX_allocation_material_batch_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_allocation_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_allocation_product_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_allocation_status");

                    b.HasIndex("OrderId", "ProductId", "MaterialBatchId")
                        .IsUnique()
                        .HasDatabaseName("IX_allocation_order_product_batch");

                    b.ToTable("Allocation", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.AppModuleDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(4);

                    b.Property<int>("TenantId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_app_module_Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_app_module_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_app_module_IsActive");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_app_module_TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_app_module_TenantId_Code_Unique");

                    b.ToTable("RefAppModule", "system");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomCategoryDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6);

                    b.HasKey("Id")
                        .HasName("PK_bom_category_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_bom_category_name");

                    b.ToTable("BomCategory", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BomCategoryId")
                        .HasColumnType("INT")
                        .HasColumnOrder(6);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnOrder(8);

                    b.Property<string>("Result")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_bom_id");

                    b.HasIndex("BomCategoryId")
                        .HasDatabaseName("IX_bom_category_id");

                    b.HasIndex("IsApproved")
                        .HasDatabaseName("IX_bom_is_approved");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_bom_name");

                    b.ToTable("Bom", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomItemDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BomId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<int>("MaterialBatchId")
                        .HasColumnType("INT")
                        .HasColumnOrder(3);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.Property<int>("WarehouseItemId")
                        .HasColumnType("INT")
                        .HasColumnOrder(4);

                    b.HasKey("Id")
                        .HasName("PK_bom_item_id");

                    b.HasIndex("BomId")
                        .HasDatabaseName("IX_bom_item_bom_id");

                    b.HasIndex("MaterialBatchId")
                        .HasDatabaseName("IX_bom_item_material_batch_id");

                    b.HasIndex("WarehouseItemId")
                        .HasDatabaseName("IX_bom_item_warehouse_item_id");

                    b.HasIndex("BomId", "MaterialBatchId", "WarehouseItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_bom_item_composite_unique");

                    b.ToTable("BomItem", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomItemDispositionDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BomItemId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("Notes")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ProcessedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_bom_item_disposition_id");

                    b.HasIndex("BomItemId")
                        .HasDatabaseName("IX_bom_item_disposition_bom_item_id");

                    b.HasIndex("Disposition")
                        .HasDatabaseName("IX_bom_item_disposition_disposition");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_bom_item_disposition_processed_on");

                    b.ToTable("BomItemDisposition", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.EnumTypeDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.HasKey("Id")
                        .HasName("PK_RefEnumType_Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_RefEnumType_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_RefEnumType_Name");

                    b.ToTable("RefEnumType", "system");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.EnumValueDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(5);

                    b.Property<int>("EnumTypeId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_RefEnumValue_Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_RefEnumValue_Code");

                    b.HasIndex("EnumTypeId");

                    b.ToTable("RefEnumValue", "system");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.MaterialBatchDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(13)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(16);

                    b.Property<string>("LocationText")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6);

                    b.Property<int>("MaterialId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnOrder(8);

                    b.Property<decimal>("RemainingQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnOrder(9);

                    b.Property<int?>("StorageSectionId")
                        .HasColumnType("INT")
                        .HasColumnOrder(10);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(15);

                    b.Property<int?>("VendorId")
                        .HasColumnType("INT")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("PK_material_batch_id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("IX_material_batch_barcode_unique")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("BatchCode")
                        .IsUnique()
                        .HasDatabaseName("IX_material_batch_batch_code_unique");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_material_batch_expiry_date");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_material_batch_is_active");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("IX_material_batch_material_id");

                    b.HasIndex("StorageSectionId")
                        .HasDatabaseName("IX_material_batch_storage_section_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_material_batch_vendor_id");

                    b.ToTable("MaterialBatch", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.MaterialDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CasNumber")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<string>("Category")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Subcategory")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(12);

                    b.HasKey("Id")
                        .HasName("PK_material_id");

                    b.HasIndex("CasNumber")
                        .HasDatabaseName("IX_material_cas_number");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_material_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_material_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_material_name");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_material_sku_unique");

                    b.HasIndex("Subcategory")
                        .HasDatabaseName("IX_material_subcategory");

                    b.ToTable("Material", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.MaterialStorageRuleDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<int>("MaterialId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<decimal>("MinQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnOrder(3);

                    b.Property<int>("PreferredSectionId")
                        .HasColumnType("INT")
                        .HasColumnOrder(5);

                    b.Property<decimal>("ThresholdQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnOrder(4);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_material_storage_rule_id");

                    b.HasIndex("MaterialId")
                        .IsUnique()
                        .HasDatabaseName("IX_material_storage_rule_material_id");

                    b.HasIndex("PreferredSectionId")
                        .HasDatabaseName("IX_material_storage_rule_preferred_section_id");

                    b.ToTable("MaterialStorageRule", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.OrganizationDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Code")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CreatedBy")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("CreatedOn")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Description")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Name")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UpdatedBy")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UpdatedOn")
                        .HasColumnOrder(8);

                    b.HasKey("Id")
                        .HasName("PK_organization_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_organization_code_unique")
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_organization_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_organization_name_unique");

                    b.ToTable("RefOrganization", "master");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.PermissionDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<int>("TenantId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_permission_Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_permission_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_permission_IsActive");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_permission_TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_permission_TenantId_Code_Unique");

                    b.ToTable("RefPermission", "system");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.ProductDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BomId")
                        .HasColumnType("INT")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_product_id");

                    b.HasIndex("BomId")
                        .HasDatabaseName("IX_product_bom_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_product_is_active");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_product_sku");

                    b.ToTable("Product", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.RoleDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.HasKey("Id")
                        .HasName("PK_RefRole_Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_RefRole_Code");

                    b.ToTable("RefRole", "system");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.RolePermissionDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(5);

                    b.Property<int>("ModuleId")
                        .HasColumnType("INT")
                        .HasColumnOrder(3);

                    b.Property<int>("PermissionId")
                        .HasColumnType("INT")
                        .HasColumnOrder(4);

                    b.Property<int>("RoleId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_role_permission_Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_role_permission_IsActive");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_role_permission_ModuleId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_role_permission_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_role_permission_RoleId");

                    b.HasIndex("RoleId", "ModuleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_role_permission_RoleId_ModuleId_PermissionId_Unique");

                    b.ToTable("RefRolePermission", "system", t =>
                        {
                            t.HasCheckConstraint("CK_role_permission_ModuleId_NotEmpty", "\"ModuleId\" != '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_role_permission_PermissionId_NotEmpty", "\"PermissionId\" != '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_role_permission_RoleId_NotEmpty", "\"RoleId\" != '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.RowLocDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AisleDOId")
                        .HasColumnType("INT");

                    b.Property<int>("AisleId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("PK_row_loc_id");

                    b.HasIndex("AisleDOId");

                    b.HasIndex("AisleId");

                    b.ToTable("RowLoc", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.StorageSectionDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("TemperatureRange")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.HasKey("Id")
                        .HasName("PK_storage_section_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_storage_section_name");

                    b.ToTable("StorageSection", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.TrayDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("INT")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<int>("RowId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<int?>("RowLocDOId")
                        .HasColumnType("INT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.HasKey("Id")
                        .HasName("PK_tray_id");

                    b.HasIndex("RowId")
                        .HasDatabaseName("IX_tray_row_id");

                    b.HasIndex("RowLocDOId");

                    b.ToTable("Tray", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.UserDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(5);

                    b.Property<int>("Gender")
                        .HasColumnType("INT")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsPasswordLinkVisited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnOrder(11);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(2);

                    b.Property<int>("NumberOfAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnOrder(10);

                    b.Property<string>("PasswordHashKey")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(8);

                    b.Property<string>("PasswordSaltKey")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(9);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(15);

                    b.HasKey("Id")
                        .HasName("PK_User_Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_User_IsActive");

                    b.HasIndex("IsPasswordSet")
                        .HasDatabaseName("IX_User_IsPasswordSet");

                    b.HasIndex("NumberOfAttempts")
                        .HasDatabaseName("IX_User_NumberOfAttempts");

                    b.ToTable("RefUser", "master", t =>
                        {
                            t.HasCheckConstraint("CK_User_NumberOfAttempts_Range", "[NumberOfAttempts] >= 0 AND [NumberOfAttempts] <= 10");

                            t.HasCheckConstraint("CK_User_PasswordFields_Consistency", "([PasswordHashKey] IS NULL AND [PasswordSaltKey] IS NULL AND [IsPasswordSet] = 0) OR ([PasswordHashKey] IS NOT NULL AND [PasswordSaltKey] IS NOT NULL AND [IsPasswordSet] = 1)");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.UserRoleDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(4);

                    b.Property<int>("RoleId")
                        .HasColumnType("INT")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_user_role_Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_user_role_IsActive");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_user_role_RoleID");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_role_UserID");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_role_UserID_RoleID");

                    b.ToTable("RefUserRole", "system", t =>
                        {
                            t.HasCheckConstraint("CK_user_role_RoleID_NotZero", "[RoleId] > 0");

                            t.HasCheckConstraint("CK_user_role_UserID_NotZero", "[UserId] > 0");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.VendorDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(2);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_Vendor_Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Vendor_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Vendor_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Vendor_Type");

                    b.ToTable("Vendor", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.VerifiedMaterialDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("EmpId")
                        .HasColumnType("INT")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsAllotted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnOrder(3);

                    b.Property<bool?>("IsQualified")
                        .HasColumnType("BIT")
                        .HasColumnOrder(7);

                    b.Property<int>("MaterialBatchId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnOrder(4);

                    b.Property<string>("Reason")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(8);

                    b.Property<string>("Specification")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(12);

                    b.HasKey("Id")
                        .HasName("PK_verified_material_id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_verified_material_created_on");

                    b.HasIndex("EmpId")
                        .HasDatabaseName("IX_verified_material_emp_id");

                    b.HasIndex("IsAllotted")
                        .HasDatabaseName("IX_verified_material_is_allotted");

                    b.HasIndex("IsQualified")
                        .HasDatabaseName("IX_verified_material_is_qualified");

                    b.HasIndex("MaterialBatchId")
                        .HasDatabaseName("IX_verified_material_material_batch_id");

                    b.ToTable("VerifiedMaterial", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.WarehouseDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("PK_warehouse_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_warehouse_name");

                    b.ToTable("Warehouse", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.WarehouseItemDO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AisleId")
                        .HasColumnType("INT")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(11);

                    b.Property<int>("MaterialBatchId")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnOrder(7);

                    b.Property<int>("RowId")
                        .HasColumnType("INT")
                        .HasColumnOrder(5);

                    b.Property<string>("Specification")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(9);

                    b.Property<int>("TrayId")
                        .HasColumnType("INT")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(13);

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INT")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("PK_warehouse_item_id");

                    b.HasIndex("AisleId");

                    b.HasIndex("MaterialBatchId")
                        .HasDatabaseName("IX_warehouse_item_material_batch_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_warehouse_item_name");

                    b.HasIndex("RowId");

                    b.HasIndex("TrayId");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_warehouse_item_warehouse_id");

                    b.HasIndex("WarehouseId", "AisleId", "RowId", "TrayId")
                        .HasDatabaseName("IX_warehouse_item_location");

                    b.ToTable("WarehouseItem", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.AisleDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.StorageSectionDO", "StorageSection")
                        .WithMany()
                        .HasForeignKey("StorageSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.DomainObjects.WarehouseDO", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_aisle_warehouse_id");

                    b.Navigation("StorageSection");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.AppModuleDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.OrganizationDO", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_app_module_TenantId");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.BomCategoryDO", null)
                        .WithMany()
                        .HasForeignKey("BomCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_bom_bom_category");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomItemDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.BomDO", null)
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bom_item_bom");

                    b.HasOne("Inventory.Domain.DomainObjects.MaterialBatchDO", null)
                        .WithMany()
                        .HasForeignKey("MaterialBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bom_item_material_batch");

                    b.HasOne("Inventory.Domain.DomainObjects.WarehouseItemDO", null)
                        .WithMany()
                        .HasForeignKey("WarehouseItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bom_item_warehouse_item");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.BomItemDispositionDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.BomItemDO", null)
                        .WithMany()
                        .HasForeignKey("BomItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bom_item_disposition_bom_item_id");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.EnumValueDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.EnumTypeDO", null)
                        .WithMany("EnumValues")
                        .HasForeignKey("EnumTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefEnumValue_RefEnumType_EnumTypeId");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.MaterialBatchDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.MaterialDO", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_material_batch_material_id");

                    b.HasOne("Inventory.Domain.DomainObjects.VendorDO", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_material_batch_vendor_id");

                    b.Navigation("Material");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.MaterialStorageRuleDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.MaterialDO", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_material_storage_rule_material");

                    b.HasOne("Inventory.Domain.DomainObjects.StorageSectionDO", null)
                        .WithMany()
                        .HasForeignKey("PreferredSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_material_storage_rule_storage_section");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.PermissionDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.OrganizationDO", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_permission_TenantId");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.ProductDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.BomDO", null)
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_product_bom_id");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.RolePermissionDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.AppModuleDO", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_role_permission_ModuleId");

                    b.HasOne("Inventory.Domain.DomainObjects.PermissionDO", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_role_permission_PermissionId");

                    b.HasOne("Inventory.Domain.DomainObjects.RoleDO", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_role_permission_RoleId");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.RowLocDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.AisleDO", null)
                        .WithMany("RowLocs")
                        .HasForeignKey("AisleDOId");

                    b.HasOne("Inventory.Domain.DomainObjects.AisleDO", null)
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_row_loc_aisle_id");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.TrayDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.RowLocDO", null)
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tray_row_id");

                    b.HasOne("Inventory.Domain.DomainObjects.RowLocDO", null)
                        .WithMany("Trays")
                        .HasForeignKey("RowLocDOId");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.UserDO", b =>
                {
                    b.OwnsOne("Inventory.Domain.ValueObjects.EmailVO", "EmailId", b1 =>
                        {
                            b1.Property<int>("UserDOId")
                                .HasColumnType("INT");

                            b1.Property<string>("EmailId")
                                .IsRequired()
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("EmailId")
                                .HasColumnOrder(4);

                            b1.HasKey("UserDOId");

                            b1.HasIndex("EmailId")
                                .IsUnique()
                                .HasDatabaseName("IX_User_EmailId");

                            b1.ToTable("RefUser", "master");

                            b1.WithOwner()
                                .HasForeignKey("UserDOId");
                        });

                    b.OwnsOne("Inventory.Domain.ValueObjects.PhoneVO", "PhoneNo", b1 =>
                        {
                            b1.Property<int>("UserDOId")
                                .HasColumnType("INT");

                            b1.Property<string>("PhoneNo")
                                .IsRequired()
                                .HasColumnType("VARCHAR(15)")
                                .HasColumnName("PhoneNo")
                                .HasColumnOrder(3);

                            b1.HasKey("UserDOId");

                            b1.HasIndex("PhoneNo")
                                .IsUnique()
                                .HasDatabaseName("IX_User_PhoneNo");

                            b1.ToTable("RefUser", "master");

                            b1.WithOwner()
                                .HasForeignKey("UserDOId");
                        });

                    b.Navigation("EmailId")
                        .IsRequired();

                    b.Navigation("PhoneNo")
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.UserRoleDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.RoleDO", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_role_RoleID");

                    b.HasOne("Inventory.Domain.DomainObjects.UserDO", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_role_UserID");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.WarehouseItemDO", b =>
                {
                    b.HasOne("Inventory.Domain.DomainObjects.AisleDO", null)
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_warehouse_item_aisle");

                    b.HasOne("Inventory.Domain.DomainObjects.MaterialBatchDO", null)
                        .WithMany()
                        .HasForeignKey("MaterialBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_warehouse_item_material_batch");

                    b.HasOne("Inventory.Domain.DomainObjects.RowLocDO", null)
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_warehouse_item_row");

                    b.HasOne("Inventory.Domain.DomainObjects.TrayDO", null)
                        .WithMany()
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_warehouse_item_tray");

                    b.HasOne("Inventory.Domain.DomainObjects.WarehouseDO", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_warehouse_item_warehouse");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.AisleDO", b =>
                {
                    b.Navigation("RowLocs");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.EnumTypeDO", b =>
                {
                    b.Navigation("EnumValues");
                });

            modelBuilder.Entity("Inventory.Domain.DomainObjects.RowLocDO", b =>
                {
                    b.Navigation("Trays");
                });
#pragma warning restore 612, 618
        }
    }
}
